---
networks:
  leaderboard-network:
    driver: bridge

services:
  # ---------------------------------------------------------------------
  # | Node.js Service                                                    | 
  # ---------------------------------------------------------------------
  leaderboard-service:
    build:
      context: ../../../
      dockerfile: .${LEADERBOARD_SERVICE_PROJECT_PATH}/Dockerfile
      args:
        - LEADERBOARD_SERVICE_PROJECT_PATH=${LEADERBOARD_SERVICE_PROJECT_PATH}
        - LEADERBOARD_NODE_PORT=${LEADERBOARD_NODE_PORT}
    ports:
      - "3000:${LEADERBOARD_NODE_PORT}"
    env_file:
      - ../../../.env
    volumes:
      - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
      - ../../../${LEADERBOARD_SERVICE_PROJECT_PATH}:/usr/src/app
    networks:
      - leaderboard-network
