---
networks:
  leaderboard-network:
    driver: bridge

services:
  # ---------------------------------------------------------------------
  # | Node.js Service                                               | 
  # ---------------------------------------------------------------------
  leaderboard-service:
    build:
      context: ../../../
      dockerfile: .${SERVICE_PROJECT_PATH}/Dockerfile
      args:
        - SERVICE_PROJECT_PATH=${SERVICE_PROJECT_PATH}
        - NODE_PORT=${NODE_PORT}
    ports:
      - "3000:${NODE_PORT}"
    env_file:
      - ../../../.env
    volumes:
      - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
      - ../../../${SERVICE_PROJECT_PATH}:/usr/src/app
    networks:
      - leaderboard-network
